### ISSUE TITLE
Configurable heading levels

### ISSUE THREAD

**Issue by janosh** [rehypejs/rehype-autolink-headings#11]
Would be nice if the heading levels to be auto-linked were configurable.

```js
options.levels: Number[] = [1, 2, 3, 4, 5, 6]
```
So if a user passes e.g. 

```js
options.levels = [2, 3, 4, 5, 6]
```

`<h1>`s should not be auto-linked.

**Comment by wooorm** [comment]
Could that be solved by a min and max? I can see people skipper h1, or h5-6, but only skipping h2 or so sounds a bit weird?

**Comment by janosh** [comment]
Would there be an advantage implementation-wise of min/max? I agree that the need to skip intermediate levels seems unlikely but why not keep full flexibility if it comes cheap?

**Comment by wooorm** [comment]
I'm thinking that it might be *too* flexible. If the use case is, skip h1, then a minDepth (or so), solves it more clearly perhaps

**Comment by janosh** [comment]
I see. Well, you decide. I'd certainly be happy either way! 😄

**Comment by remcohaszing** [comment]
Seems useful!

I'm with @janosh's original proposal, as it's easy to understand and implement. Although I'm ok with using `minDepth` as well.

The type could be narrowed down to:

```ts
Array<1 | 2 | 3 | 4 | 5 | 6>
```

**Comment by wooorm** [comment]
To add an example for my stance, `mdast-util-toc` and `remark-toc` use `maxDepth`: https://github.com/syntax-tree/mdast-util-toc#optionsmaxdepth.

If we go with `levels`, I’d also like to discuss the naming. Headings currently use `depth`, although I’d prefer `rank` (which is what HTML, and thus hast, uses).
It’s quite hard to change a field in mdast at this point, so maybe that’ll never happen on mdast heading nodes, but as this is a hast/rehype plugin, we don’t have to worry about that, and some version of `rank` would be my preference.

**Comment by remcohaszing** [comment]
> To add an example for my stance, `mdast-util-toc` and `remark-toc` use `maxDepth`: https://github.com/syntax-tree/mdast-util-toc#optionsmaxdepth.

I think consistency is a strong argument.

**Comment by janosh** [comment]
Depth I think is equally widely used as level in this context. Rank I haven't come across much so my feeling is it would be less obvious to users what is meant.

**Comment by ChristianMurphy** [comment]
An alternative, what about allowing a `unist-util-is` compatible test to be passed in?
Which could allow for any form of filtering on heading nodes, including depth/rank based, but also content base and more.

**Comment by janosh** [comment]
@ChristianMurphy That would be really cool. What does 'and more' entail? I'm asking specifically because I could see a use case for specifying e.g. a CSS selector like `main > :where(h1, h2, h3, h4, h5, h6)` to only auto-link headings that are in the main text as opposed to headings in side bars etc.

**Comment by ChristianMurphy** [comment]
> What does 'and more' entail?

It means anything that can be specified with https://github.com/syntax-tree/unist-util-is#function-testnode-index-parent

> a CSS selector like

https://github.com/syntax-tree/hast-util-select could  offer some of that.
I'm not sure your specific example would work in this contexty, as the test works on a specific node, rather than the entire tree, but conceptually it may be possible.

**Comment by wooorm** [comment]
I think either a `hast-util-is-element` or a `unist-util-is` based test might be great! The earlier use cases could be `test: ['h2', 'h3', 'h4', 'h5', 'h6']`. And some much more advanced cases could be handled, like ignoring one or more headings based on their contents.

**Comment by wooorm** [comment]
Released the test! https://github.com/rehypejs/rehype-autolink-headings/releases/tag/6.1.0

**Comment by janosh** [comment]
[Works great](https://github.com/janosh/svelte-toc/commit/56ba0cb25faa6b7628185e12091fbb4dd5d4d0dd)! Thanks!
