### ISSUE TITLE
Classname merge is glitched

### ISSUE THREAD

**Issue by gustaveWPM** [rehypejs/rehype-autolink-headings#22]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

```ts
        rehypeAutolinkHeadings,
        {
          behavior: 'prepend',
          properties: {
            class: 'autolink-header mr-2',
            ariaHidden: false,
            tabIndex: 0
          },
          content: [
            h('span.sr-only', 'permalink'),
            s(
              'svg.autolink-svg.m-auto.h-full.mr-2',
              {
                xmlns: 'http://www.w3.org/2000/svg',
                width: 24,
                height: 24,
                fill: 'currentColor',
                viewBox: '0 0 24 24'
              },
              s('path', {
                d: 'M9.199 13.599a5.99 5.99 0 0 0 3.949 2.345 5.987 5.987 0 0 0 5.105-1.702l2.995-2.994a5.992 5.992 0 0 0 1.695-4.285 5.976 5.976 0 0 0-1.831-4.211 5.99 5.99 0 0 0-6.431-1.242 6.003 6.003 0 0 0-1.905 1.24l-1.731 1.721a.999.999 0 1 0 1.41 1.418l1.709-1.699a3.985 3.985 0 0 1 2.761-1.123 3.975 3.975 0 0 1 2.799 1.122 3.997 3.997 0 0 1 .111 5.644l-3.005 3.006a3.982 3.982 0 0 1-3.395 1.126 3.987 3.987 0 0 1-2.632-1.563A1 1 0 0 0 9.201 13.6zm5.602-3.198a5.99 5.99 0 0 0-3.949-2.345 5.987 5.987 0 0 0-5.105 1.702l-2.995 2.994a5.992 5.992 0 0 0-1.695 4.285 5.976 5.976 0 0 0 1.831 4.211 5.99 5.99 0 0 0 6.431 1.242 6.003 6.003 0 0 0 1.905-1.24l1.723-1.723a.999.999 0 1 0-1.414-1.414L9.836 19.81a3.985 3.985 0 0 1-2.761 1.123 3.975 3.975 0 0 1-2.799-1.122 3.997 3.997 0 0 1-.111-5.644l3.005-3.006a3.982 3.982 0 0 1 3.395-1.126 3.987 3.987 0 0 1 2.632 1.563 1 1 0 0 0 1.602-1.198z'
              })
            )
          ]
```

### Expected behavior

`cn('autolink-svg m-auto h-full mr-2', 'autolink-header mr-2')`

(More infos: https://www.youtube.com/watch?v=re2JFITR7TI)

### Actual behavior

`'autolink-svg m-auto h-full mr-2' + ' ' + 'autolink-header mr-2'`

(This results in a conflict: both `m-auto` and `mr-2` are in the classList.)

### Runtime

Node v17

### Package manager

yarn 1

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
It’s `className: ['autolink-header', 'mr-2']`; more info on properties here: https://github.com/syntax-tree/hast#properties
