### ISSUE TITLE
add plaintext to content

### ISSUE THREAD

**Issue by A1ca7raz** [rehypejs/rehype-autolink-headings#24]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I don't want any extra elements in the link element. I want to add plaintext to the link element.

### Solution

String should be accepted in option `content`.

### Alternatives

 n

**Comment by ChristianMurphy** [comment]
Welcome @A1ca7raz! 👋 
Could you give an example of your expected input and output?
Could you also give some context on why you want the output to change?

**Comment by A1ca7raz** [comment]
Sorry. I just found out that `content: { type: 'text', value: '' }` could work.
