### ISSUE TITLE
State that rehype-slug is required

### ISSUE THREAD

**Issue by estevanmaito** [rehypejs/rehype-autolink-headings#4]
### Subject of the feature

It's not documented that `rehype-slug` is required for `rehype-autolink-headings` to work.

### Problem

I'm not familiar with rehype, its dependencies and etc. so I got into this problem while using `next-mdx-enhanced` and found out that I was not alone:

https://github.com/hashicorp/next-mdx-enhanced/issues/56 (OP closed issue without comments)
https://github.com/hashicorp/next-mdx-enhanced/issues/62

It's not clear that `rehype-slug` is a required dependency. I saw the examples and thought of it just as mere examples, as my usage differs from it, eg.:

```js
module.exports = withMdxEnhanced({
  layoutPath: 'layouts',
  fileExtensions: ['mdx'],
  remarkPlugins: [],
  rehypePlugins: [require('rehype-slug'), require('rehype-autolink-headings')],
  extendFrontMatter: {
    process: (mdxContent, frontMatter) => {},
    phase: 'prebuild|loader|both',
  },
})()
```

### Expected behavior

Add a note to install instructions:

*Note that `rehype-slug` is required and should be used/invoked before `rehype-autolink-headings`

**Comment by wooorm** [comment]
Hi Estevan, thanks for reporting and working on a fix!
